eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769

spring:
  profiles:
    active: dev
  application:
    name: service-zuul
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://programmer-tool-reader  # 后端服务名
          predicates:
            - Path=/redis/**   # 路由地址
          filters:
            - name: AuthenticationFilter  # 身份认证
            - name: AuthorizationFilter   # 用户鉴权
            - StripPrefix=1 # 去掉前缀