eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  host:
    connect-timeout-millis: 15000
  routes:
    read:
      path: /api-read/**
      serviceId: programmer-tool-main
    redis:
      path: /api-redis/**
      serviceId: programmer-tool-reader